# Run Terraform for OCI with Azure agent on OCI

trigger:
- main

pool:
  name: oci-vm

steps:
- script: |
    cd terraform
    terraform init
    # terraform plan
    terraform apply -auto-approve
    terraform destroy -auto-approve

  displayName: 'Run Terraform'
